import { Profile } from '@/types/profile';
import { Project } from '@/types/project';
import { Experience } from '@/types/experience';
import { SkillCategory } from '@/types/skill';

export const MOCK_PROFILE: Profile = {
  name: 'Lê Tuấn Nhật',
  title: 'Backend (Golang) & Blockchain Engineer',
  tagline: 'Backend development with Golang, Layer 1 blockchain systems, and Rust/QUIC protocols.',
  summary:
    'Backend Engineer with 1.5 years of professional experience developing core blockchain systems. Strong foundation in multi-threading, concurrency, and database optimization gained from optimizing a Layer 1 blockchain to handle 12,000 TPS. Additionally, I have solid experience building robust RESTful APIs using Java (Spring Boot), Go, Node.js (Express/NestJS), and TypeScript, integrated with databases (MongoDB, PostgreSQL, MySQL), optimizing database queries, and ensuring system reliability through deep debugging and unit testing.',
  location: 'Hồ Chí Minh, Vietnam',
  email: 'letuannhat105@gmail.com',
  phone: '0944477357',
  github: 'https://github.com/PearTNhat',
  githubUsername: 'PearTNhat',
  resumeUrl: '/cv/CV-LeTuanNhat-Go.pdf',
  resumes: [
    {
      id: 'cv-go',
      label: 'CV Golang Backend',
      role: 'Backend Engineer (Go)',
      badge: 'REST API, gRPC & Databases',
      url: '/cv/CV-LeTuanNhat-Go.pdf',
      filename: 'CV-LeTuanNhat-Go.pdf',
    },
    {
      id: 'cv-blockchain',
      label: 'CV Blockchain Engineer',
      role: 'Blockchain & EVM Developer',
      badge: 'Layer 1, Consensus & Web3',
      url: '/cv/CV-LeTuanNhat-Blockchain.pdf',
      filename: 'CV-LeTuanNhat-Blockchain.pdf',
    },
  ],
  highlights: [
    'Core Layer 1 blockchain developer; engineered high-throughput consensus & transaction execution pipeline achieving 12,000 TPS.',
    'Deep technical expertise in multi-threading debugging, concurrency bottlenecks, race condition elimination, and deadlock mitigation.',
    'Architected low-level dual-trie state storage engine (NOMT Trie, Flat Trie, LevelDB, Xapian).',
    'Built distributed chunked transfer via Rust/QUIC and high-performance backend microservices (Go, gRPC, Java Spring Boot).',
  ],
  education: {
    institution: 'Posts and Telecommunications Institute of Technology (PTIT)',
    degree: 'Engineer in Information Technology',
    period: '2021 - 2026',
    major: 'Information Technology',
  },
  stats: [
    {
      id: 'stat-yoe',
      label: 'Experience',
      value: '~1.5 YOE',
      description: 'Blockchain & Go backend',
      highlight: 'Core Systems',
    },
    {
      id: 'stat-tps',
      label: 'Peak Throughput',
      value: '12,000 TPS',
      description: 'Layer 1 transaction engine',
      highlight: 'High Performance',
    },
    {
      id: 'stat-systems',
      label: 'Production Systems',
      value: '6 Core Systems',
      description: 'L1 Chain, Go Microservices, Rust QUIC, RPC, MERN',
      highlight: 'Fullstack & Systems',
    },
    {
      id: 'stat-english',
      label: 'English Proficiency',
      value: 'Pre-Intermediate',
      description: 'Good technical reading, Pre-Intermediate speaking',
      highlight: 'Technical English',
    },
  ],
  socials: [
    {
      platform: 'github',
      label: 'GitHub',
      value: 'github.com/PearTNhat',
      href: 'https://github.com/PearTNhat',
      icon: 'Github',
    },
    {
      platform: 'email',
      label: 'Email',
      value: 'letuannhat105@gmail.com',
      href: 'mailto:letuannhat105@gmail.com',
      icon: 'Mail',
    },
    {
      platform: 'phone',
      label: 'Phone',
      value: '0944477357',
      href: 'tel:0944477357',
      icon: 'Phone',
    },
    {
      platform: 'location',
      label: 'Location',
      value: 'Hồ Chí Minh, Vietnam',
      href: '#contact',
      icon: 'MapPin',
    },
  ],
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-metanode',
    slug: 'metanode-blockchain',
    title: 'MetaNode Blockchain',
    subtitle: 'High-Throughput Layer 1 Blockchain Engine & RPC Gateway',
    type: 'commercial',
    category: 'blockchain',
    featured: true,
    order: 1,
    period: '05/2025 - Present',
    role: 'Core Layer 1 Blockchain Developer',
    badgeText: 'Commercial • 12K TPS',
    verificationStatus: 'Production System',
    githubUrl: 'https://github.com/x3pi/metanode',
    description:
      'High-performance Layer 1 blockchain system with extensive core module contributions: optimized the concurrent transaction execution pipeline and DAG/BFT consensus engine to reach a peak throughput of 12,000 TPS. Actively investigated, debugged, and eliminated complex multi-threading bottlenecks, thread contention, and distributed race conditions.',
    metrics: [
      { label: 'Throughput', value: '12,000 TPS' },
      { label: 'Consensus', value: 'DAG + BFT' },
      { label: 'State Storage', value: 'NOMT & Flat Trie' },
    ],
    technologies: [
      'Go',
      'Rust',
      'gRPC / Protobuf',
      'JSON-RPC',
      'DAG',
      'BFT',
      'NOMT Trie',
      'Flat Trie',
      'LevelDB',
      'TCP P2P',
      'cgo / FFI',
      'Linux',
    ],
    contributions: [
      'Extensively developed and optimized core execution layers and DAG + BFT consensus engines in Go and Rust, driving network throughput to a peak of 12,000 TPS.',
      'Spearheaded deep multi-threading debugging: identified and eradicated severe race conditions, mutex contention, and deadlocks across parallel transaction validation pipelines.',
      'Eliminated P2P/TCP network queue congestion and buffer bottlenecks during continuous block propagation across distributed validator nodes.',
      'Architected dual-layer state storage utilizing NOMT Trie, Flat Trie, LevelDB, and Xapian indexer, drastically minimizing disk I/O latency under heavy transactional loads.',
      'Engineered high-availability Ethereum JSON-RPC 2.0 gateways and internal gRPC (Protobuf) services for ultra-low-latency client interactions.',
      'Investigated and resolved thread synchronization, goroutine leaks, and memory safety issues at the FFI/cgo boundary between Go execution runtime and Rust cryptographic crates.',
    ],
    architecture: {
      title: 'DAG Ordering + BFT Quorum Concurrency-Optimized Pipeline',
      description:
        'Combines Directed Acyclic Graph (DAG) for asynchronous transaction ordering and BFT consensus for deterministic finality, with an optimized dual-trie state structure on LevelDB fine-tuned against thread contention.',
      points: [
        'Concurrent multi-stage transaction verification with fine-grained locking to eradicate CPU scheduling bottlenecks.',
        'Asynchronous DAG ordering with BFT quorum consensus achieving sub-second block finality without I/O stalls.',
        'Zero-copy FFI/cgo bindings with strict thread-safety between Go execution layers and Rust cryptographic modules.',
      ],
    },
  },
  {
    id: 'proj-quic-storage',
    slug: 'rust-quic-storage',
    title: 'File Storage System (Rust & QUIC)',
    subtitle: 'Chunk-Based Distributed File Storage over QUIC Protocol',
    type: 'commercial',
    category: 'storage',
    featured: true,
    order: 2,
    period: '2025',
    role: 'Systems Developer',
    badgeText: 'Commercial • Rust & QUIC',
    verificationStatus: 'Production System',
    githubUrl: 'https://github.com/x3pi/file-storage',
    description:
      'High-performance distributed file storage system built with Rust and the QUIC transport protocol, featuring parallel chunk upload/download, cryptographic Merkle Tree integrity validation, and smart contract audit trails.',
    metrics: [
      { label: 'Protocol', value: 'QUIC / UDP' },
      { label: 'Integrity', value: 'Merkle Tree' },
      { label: 'Smart Contract', value: 'Solidity Audit' },
    ],
    technologies: [
      'Rust',
      'QUIC Protocol',
      'Merkle Tree',
      'Smart Contracts',
      'Solidity',
      'Tokio Async',
      'UDP Sockets',
    ],
    contributions: [
      'Engineered a high-performance client-server storage architecture using Rust and the QUIC protocol to completely eliminate TCP Head-of-Line (HoL) blocking over volatile networks.',
      'Designed a fixed-size chunk streaming mechanism with cryptographic Merkle Tree proof generation, verifying chunk validity without buffering entire files in memory.',
      'Integrated Ethereum Solidity smart contracts on-chain to immutably store file metadata, verify cryptographic proofs, and record user download activities for auditability.',
      'Conducted extensive network stress testing, handled packet loss and timeout scenarios, and benchmarked transfer throughput with multi-gigabyte files.',
    ],
    architecture: {
      title: 'QUIC Chunk-Streaming with Cryptographic Merkle Verification',
      description:
        'Files are split into fixed-size chunks, hashed into an on-chain recorded Merkle root, and streamed concurrently over multiplexed QUIC streams.',
      points: [
        'Multiplexed bidirectional stream management avoiding TCP head-of-line blocking.',
        'Zero-copy chunk verification using cryptographic Merkle branch proofs.',
        'Immutable on-chain metadata state validation and activity tracking.',
      ],
    },
  },
  {
    id: 'proj-ecom-microservices',
    slug: 'golang-ecommerce-microservices',
    title: 'Golang E-Commerce Microservices Platform',
    subtitle: 'High-Concurrency Golang Microservices with Kafka, RabbitMQ, Redis & Graylog',
    type: 'personal',
    category: 'ecommerce',
    featured: true,
    order: 3,
    period: '2025 - 2026',
    role: 'Fullstack Developer',
    teamSize: 1,
    badgeText: 'Go Microservices • Event-Driven',
    verificationStatus: 'Open Source Repo',
    githubUrl: 'https://github.com/PearTNhat/microservice-base',
    description:
      'A high-throughput distributed e-commerce backend platform built with Go adhering to Clean Architecture and Domain-Driven Design (DDD). Features an API Gateway reverse proxy, atomic Redis Lua scripts for overselling-free Flash Sales, Apache Kafka for high-throughput batching of product views, RabbitMQ DLX for resilient asynchronous order processing, and centralized observability via Graylog and OpenSearch.',
    metrics: [
      { label: 'Architecture', value: 'Clean DDD & gRPC' },
      { label: 'Event Streaming', value: 'Kafka & RabbitMQ' },
      { label: 'Concurrency', value: 'Redis Lua & Singleflight' },
    ],
    technologies: [
      'Go',
      'Go Fiber',
      'gRPC / Protobuf',
      'PostgreSQL',
      'Redis',
      'Apache Kafka',
      'RabbitMQ',
      'Graylog',
      'OpenSearch',
      'Docker',
      'Clean Architecture',
      'Asynq',
    ],
    contributions: [
      'Architected an independent Monorepo microservices ecosystem (API Gateway, User, Product, Order) adhering strictly to Domain-Driven Design (DDD) and Clean Architecture principles.',
      'Engineered an atomic Flash Sale checkout mechanism using Redis Lua scripts and Idempotency-Key middlewares, effectively preventing inventory overselling and duplicate order submission.',
      'Eliminated Cache Stampede (Thundering Herd) on high-traffic product catalog queries by implementing Redis Cache-Aside combined with Go singleflight.',
      'Integrated Apache Kafka for periodic batch aggregation of product view statistics and RabbitMQ (Topic Exchange & Dead Letter Queue) for resilient asynchronous order task pipelines.',
      'Constructed end-to-end centralized observability and structured logging pipelines transmitting GELF UDP packets to Graylog & OpenSearch with correlation via X-Request-ID trace IDs.',
    ],
    architecture: {
      title: 'Event-Driven Microservices with Distributed Cache & Message Brokers',
      description:
        'A decoupled microservices ecosystem utilizing Go Fiber API Gateway for reverse proxying, Redis for high-speed atomic caching and locking, Kafka & RabbitMQ for event-driven asynchronous processing, and PostgreSQL for transactional integrity.',
      points: [
        'Decoupled monolithic services into independent Go microservice binaries with gRPC and RESTful endpoints.',
        'High-concurrency peak clipping with Redis atomic Lua scripts and RabbitMQ background workers.',
        'Structured logging and distributed tracing across all gateway and microservice boundaries using Graylog.',
      ],
    },
  },
  {
    id: 'proj-metacosign',
    slug: 'metacosign-rpc',
    title: 'MetaCoSign - Web3 JSON-RPC Gateway',
    subtitle: 'Ethereum Standard JSON-RPC 2.0 Gateway & BLS Key Management',
    type: 'commercial',
    category: 'blockchain',
    featured: true,
    order: 4,
    period: '2025',
    role: 'Blockchain Developer',
    badgeText: 'Commercial • JSON-RPC',
    verificationStatus: 'Production System',
    githubUrl: 'https://github.com/x3pi/MetaCoSign',
    description:
      'High-availability Ethereum standard JSON-RPC 2.0 gateway written in Go, serving high-throughput Web3 wallet/DApp connectivity, request routing, response caching, and cryptographic BLS key registration for network validators.',
    metrics: [
      { label: 'Standard', value: 'JSON-RPC 2.0' },
      { label: 'Compatibility', value: 'Ethereum Geth' },
      { label: 'Security', value: 'BLS Signatures' },
    ],
    technologies: [
      'Go',
      'JSON-RPC 2.0',
      'Geth',
      'BLS Signatures',
      'React.js',
      'Docker',
    ],
    contributions: [
      'Developed high-availability JSON-RPC 2.0 gateway services in Go implementing standard Ethereum specifications (eth_*, net_*, web3_*).',
      'Built a secure BLS key registration pipeline and cryptographic signature verification for network validators.',
      'Optimized concurrent RPC request throughput and ensured data consistency across distributed node clusters.',
      'Integrated React.js administrative dashboard and containerized the gateway service using Docker for production deployment.',
    ],
    architecture: {
      title: 'Ethereum JSON-RPC 2.0 Gateway Architecture',
      description:
        'Converts standard Ethereum Web3 calls into internal node commands, integrating response caching and BLS signature validation.',
      points: [
        'Full compatibility with standard Web3 tooling (MetaMask, ethers.js, Foundry).',
        'Cryptographic BLS key registration and multi-party signature validation pipeline.',
      ],
    },
  },
  {
    id: 'proj-stationery-store',
    slug: 'stationery-ecommerce-platform',
    title: 'Stationery E-Commerce Platform',
    subtitle: 'Enterprise E-Commerce System with Java Spring Boot, Spring Security, Gemini AI & MoMo',
    type: 'personal',
    category: 'ecommerce',
    featured: true,
    order: 5,
    period: '01/04/2025 - Present',
    role: 'Fullstack Developer',
    teamSize: 4,
    badgeText: 'Team Project • Java Spring Boot',
    verificationStatus: 'Open Source Repo',
    githubUrl: 'https://github.com/PearTNhat/Stationery-web-client',
    githubServerUrl: 'https://github.com/PearTNhat/stationery-be-server',
    description:
      'A comprehensive stationery e-commerce platform built with Java Spring Boot and React, featuring secure OAuth2 authentication, Google Gemini AI smart shopping assistant, image-based search, and MoMo digital payment integration.',
    metrics: [
      { label: 'Backend', value: 'Java & Spring Boot' },
      { label: 'Security', value: 'OAuth2 & Spring Security' },
      { label: 'AI & Payment', value: 'Gemini AI & MoMo' },
    ],
    technologies: [
      'Java',
      'Spring Boot',
      'Spring Security',
      'OAuth2 Client',
      'MySQL',
      'ReactJS',
      'TypeScript',
      'Redux',
      'TailwindCSS',
      'Google Gemini AI',
      'MoMo API',
      'Cloudinary',
      'Docker',
    ],
    contributions: [
      'Engineered scalable RESTful API services using Java Spring Boot and relational schema modeling with MySQL.',
      'Implemented robust multi-provider authentication using Spring Security and OAuth2 Client (Google & Email login, password reset).',
      'Integrated Google Gemini AI chatbot for 24/7 conversational customer guidance and automated product inquiries.',
      'Developed image-based visual product search and historical search tracking for enhanced user experience.',
      'Integrated MoMo payment gateway IPN webhook for secure, real-time transaction processing.',
      'Built a full-featured admin management dashboard for products, user accounts, orders, discount vouchers, and multi-attribute product variants (color, size, category).',
    ],
    architecture: {
      title: 'Decoupled Client-Server Architecture with Spring Boot & AI Integrations',
      description:
        'A layered enterprise architecture featuring React SPA frontend consuming Java Spring Boot RESTful APIs, protected with Spring Security filter chains and connected to cloud AI & payment services.',
      points: [
        'Role-Based Access Control (RBAC) and security filter chains with Spring Security & OAuth2.',
        'Intelligent conversational shopping assistant powered by Google Gemini AI API.',
        'Reliable payment transaction workflows via MoMo Payment Gateway IPN webhook.',
        'High-performance cloud media management with Cloudinary.',
      ],
    },
  },
  {
    id: 'proj-laptop-store',
    slug: 'laptop-ecommerce-website',
    title: 'Laptop E-Commerce Platform',
    subtitle: 'Fullstack MERN Store with AI Recommendations & MoMo Payment',
    type: 'personal',
    category: 'ecommerce',
    featured: true,
    order: 6,
    period: '01/09/2024 - 04/12/2024',
    role: 'Fullstack Developer',
    teamSize: 1,
    badgeText: 'Personal Project • Fullstack',
    verificationStatus: 'Live Demo',
    githubUrl: 'https://github.com/PearTNhat/laptop-store-client',
    githubServerUrl: 'https://github.com/PearTNhat/laptop-store-server',
    liveUrl: 'https://laptop-ltn105-store.vercel.app/',
    description:
      'A fullstack e-commerce web platform for browsing and purchasing laptops, featuring AI-powered personalized product recommendations, real-time reviews via Socket.IO, integrated MoMo payment gateway, and an administrative management dashboard.',
    metrics: [
      { label: 'Frontend', value: 'React + Redux' },
      { label: 'Real-Time', value: 'Socket.IO' },
      { label: 'Payment', value: 'MoMo Gateway' },
    ],
    technologies: [
      'ReactJS',
      'Redux',
      'TailwindCSS',
      'Socket.IO',
      'Node.js',
      'Express',
      'MongoDB',
      'JWT',
      'Multer',
      'Nodemailer',
      'Cloudinary',
      'MoMo API',
    ],
    contributions: [
      'Built responsive user interface with ReactJS, Redux state management, and TailwindCSS for smooth shopping experiences.',
      'Developed RESTful API with Node.js/Express, MongoDB schemas, JWT authentication, and automated password recovery via Nodemailer.',
      'Integrated Socket.IO for real-time bidirectional customer reviews, comments, and live ratings.',
      'Implemented AI-assisted product recommendation module suggesting relevant laptops based on user preferences and search behavior.',
      'Integrated MoMo payment gateway API for secure, automated checkout transactions.',
      'Utilized Multer and Cloudinary for high-performance asynchronous image upload and media management.',
      'Built dedicated Admin Dashboard to manage products, users, inventory, and order statuses.',
    ],
    architecture: {
      title: 'Fullstack MERN Architecture with Real-Time WebSockets & Cloud Integrations',
      description:
        'Decoupled client-server architecture with React SPA on Vercel connecting to Node.js/Express API, MongoDB database, Socket.IO event gateway, and cloud media services.',
      points: [
        'State management with Redux Toolkit for seamless cart, authentication, and wishlist synchronization.',
        'Secure JWT authentication with bcrypt password hashing and Nodemailer verification workflows.',
        'Real-time bidirectional event bus using Socket.IO for instant user reviews and live updates.',
        'Automated IPN payment handling with MoMo payment gateway.',
      ],
    },
  },
];

export const MOCK_EXPERIENCE: Experience[] = [
  {
    id: 'exp-be-earning',
    company: 'BE-EARNING JOINT STOCK COMPANY',
    position: 'Blockchain Developer',
    location: 'Hồ Chí Minh, Vietnam',
    startDate: '05/2025',
    endDate: 'Current',
    current: true,
    summary:
      'Core Layer 1 Blockchain & Backend Engineer: Extensively developed and optimized the high-throughput Layer 1 network to achieve 12,000 TPS. Specialized in deep multi-threading debugging, concurrency bottleneck elimination, low-level state storage, and distributed Rust/QUIC file protocols.',
    technologies: [
      'Go',
      'Rust',
      'EVM',
      'DAG',
      'BFT',
      'NOMT Trie',
      'LevelDB',
      'Xapian',
      'QUIC',
      'JSON-RPC',
      'Docker',
    ],
    projects: [
      {
        name: 'Layer 1 Core & Distributed Systems Development',
        role: 'Core Layer 1 Blockchain & Backend Developer',
        technologies: ['Go', 'Rust', 'EVM', 'DAG', 'BFT', 'LevelDB', 'QUIC', 'TCP P2P'],
        description: 'Developed multi-node consensus, parallel transaction pipelines, state storage, and chunked storage systems.',
        contributions: [
          'Engineered core execution and DAG/BFT consensus mechanism supporting up to 12,000 TPS throughput.',
          'Spearheaded deep multi-threading debugging, resolving critical race conditions, deadlocks, and mutex contention under high-concurrency workloads.',
          'Optimized TCP P2P networking and inter-node block streaming to eliminate queue blocking and buffer congestion.',
          'Developed NOMT Trie & LevelDB integration for low-latency state retrieval.',
          'Implemented client-server QUIC file transfer with Merkle Tree verification in Rust.',
          'Maintained Ethereum-compatible JSON-RPC APIs and internal gRPC services in Go.',
        ],
      },
    ],
  },
];

export const MOCK_SKILLS: SkillCategory[] = [
  {
    id: 'core-languages',
    title: 'Core Systems & Backend',
    subtitle: 'Primary languages & concurrency models',
    icon: 'Terminal',
    skills: [
      { name: 'Go (Golang)', note: 'Goroutines, channels, cgo, clean arch' },
      { name: 'Java', note: 'Spring Boot, Spring Security, REST APIs, JPA/Hibernate' },
      { name: 'Rust', note: 'Ownership, async Tokio, QUIC, memory safety' },
      { name: 'C / C++', note: 'FFI, low-level pointers & performance' },
      { name: 'TypeScript / Node', note: 'Fullstack tooling, Next.js, API clients' },
      { name: 'Python', note: 'Automation, scripting, benchmarks' },
    ],
  },
  {
    id: 'blockchain-evm',
    title: 'Blockchain & Consensus',
    subtitle: 'L1 architecture, EVM, cryptographic proofs',
    icon: 'Layers',
    skills: [
      { name: 'Go-ethereum (Geth)', note: 'Core EVM internals, state trie' },
      { name: 'DAG & BFT Consensus', note: 'Multi-node distributed consensus' },
      { name: 'Ethereum JSON-RPC 2.0', note: 'Standard RPC methods & Web3 SDKs' },
      { name: 'Solidity & EVM Bytecode', note: 'Smart contract execution & receipts' },
      { name: 'NOMT Trie & Flat Trie', note: 'High-speed blockchain state storage' },
      { name: 'Merkle Trees & BLS Keys', note: 'Cryptographic proofs & signatures' },
    ],
  },
  {
    id: 'storage-databases',
    title: 'Databases & State Engines',
    subtitle: 'Key-value, search engines & relational stores',
    icon: 'Database',
    skills: [
      { name: 'LevelDB', note: 'LSM-tree engine for blockchain state' },
      { name: 'Xapian Indexer', note: 'High-speed fulltext search engine' },
      { name: 'PostgreSQL', note: 'Complex querying, indexing, ACID transactions' },
      { name: 'MySQL', note: 'Relational data modeling & optimization' },
      { name: 'Redis', note: 'In-memory caching, distributed locks' },
      { name: 'MongoDB', note: 'Document model & aggregations' },
    ],
  },
  {
    id: 'infra-networking',
    title: 'Networking, Protocols & Infra',
    subtitle: 'Distributed transport, streaming & containerization',
    icon: 'Cpu',
    skills: [
      { name: 'TCP / UDP Sockets', note: 'Low-level socket programming, connection pooling' },
      { name: 'HTTP / REST APIs', note: 'High-throughput HTTP/1.1 & HTTP/2, middleware design' },
      { name: 'QUIC Protocol', note: 'Multiplexed UDP stream transport in Rust' },
      { name: 'gRPC & Protocol Buffers', note: 'High-throughput binary RPC' },
      { name: 'Apache Kafka', note: 'Event-driven streaming & partition queues' },
      { name: 'Docker', note: 'Containerization, multi-stage builds' },
      { name: 'Linux Systems', note: 'System tuning, kernel sockets, CI/CD' },
      { name: 'RabbitMQ', note: 'Message brokers & task queues' },
    ],
  },
];
